blank_issues_enabled: false
contact_links:
  - name: Aidbox user chat
    url: https://bit.ly/3j4xqO5
    about: Ask questions, discuss issues and features
  - name: Aidbox documentation
    url: https://bit.ly/2UptNrH
    about: Check Aidbox docs first if you have any questions
